name: "Automate Program"

description: "Automate program related issues"

inputs:
  OWNER:
    description: "repo owner"
    required: true
    default: "codinasion"

  REPO:
    description: "repo name"
    required: true
    default: "program"

  TOKEN:
    description: "github token"
    required: true

  USERNAME:
    description: "github username"
    required: true

  ISSUE_NUMBER:
    description: "issue number"
    required: true

  ISSUE_TITLE:
    description: "issue title"
    required: true

  ISSUE_BODY:
    description: "issue body"
    required: true

  ISSUE_LABEL:
    description: "issue label"
    required: true

  SUBMIT_PROGRAM:
    description: "submit a program"
    required: true
    default: "false"

  SUBMIT_PROGRAM_COMMENT_CLOSE:
    description: "comment & close for submit program issue"
    required: true
    default: "false"

  AUTO_CREATE_ISSUE:
    description: "create track issue"
    required: true
    default: "false"

  AUTO_TRACK_ISSUE:
    description: "auto create good first issue"
    required: true
    default: "false"

  AUTO_ASSIGN_ISSUE:
    description: "auto assign issue"
    required: true
    default: "false"

  ######################################################
  ##        Collect Program Data Related Inputs       ##
  ######################################################
  PROGRAM_REPO:
    description: "name of program repository"
    required: true
    default: "program"

  PROGRAM_REPO_FOLDER:
    description: "folder name of program repository"
    required: true
    default: "program"

  COLLECT_PROGRAM_DATA:
    description: "collect program data"
    required: true
    default: "false"

runs:
  using: "node16"
  main: "../action.js"
