export * from "./add-matrices";
export * from "./are-anagrams";
export * from "./calculate-compound-interest";
export * from "./calculate-simple-interest";
export * from "./combination";
export * from "./factorial";
export * from "./is-armstrong-number";
export * from "./is-even";
export * from "./is-float";
export * from "./is-integer";
export * from "./is-leap-year"
export * from "./is-odd";
export * from "./is-palindrome"
export * from "./is-pangram"
export * from "./is-prime"
export * from "./permutation";
export * from "./string-to-integer"
