name: 🐛 Bug
description: Report an issue to help improve the project.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Hey Geek !!!** 

        This is an open source repository.

        * For questions, ask in [Discussions](https://github.com/orgs/codinasion/discussions).
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/codinasion/program/issues).

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue
    validations:
      required: true

  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the Codinasion project's [Code of Conduct](CODE_OF_CONDUCT.md)
          required: true
