name: 📄 Documentation issue
description: Found an issue in the documentation
title: "[DOCS]: "
labels: ["documentation"]
assignees: ["harshraj8843"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this documentation-related issue hasn't been already submitted by someone by looking through other open/closed issues

        For any query, ask in [Discussions](https://github.com/orgs/codinasion/discussions)

  - type: textarea
    id: description
    attributes:
      label: Description of the issue
      description: Give a brief description of what happened and what should have happened
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Please provide any additional information such as logs, screenshots, links, and scenarios in which the issue occurs to facilitate resolving the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the project's [Code of Conduct](https://github.com/codinasion/.github/blob/master/CODE_OF_CONDUCT.md)
          required: true
