name: Submit Program
description: Submit New Program
labels: ["add-program"]
body:
  - type: markdown
    attributes:
      value: |
        **Hey Geek !!!** 

        This is an open source repository.

        * For questions, ask in [Discussions](https://github.com/orgs/codinasion/discussions).
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/codinasion/program/issues).
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the program
    validations:
      required: false
