import type { LanguageDataType } from "./type";

const LanguageData: LanguageDataType[] = [
  {
    name: "C",
    fileExtension: ["c", "cats", "h", "idc", "w"],
    namingConvention: "PascalCase",
    prismTag: "c",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/db2101f6-0bde-46ea-a20a-1d724f4b225a",
  },
  {
    name: "C#",
    fileExtension: ["cs", "cake", "cshtml", "csx"],
    namingConvention: "PascalCase",
    prismTag: "csharp",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/7c1c6b28-37ba-4871-afe0-3c8faee97b45",
  },
  {
    name: "C++",
    fileExtension: [
      "cpp",
      "c++",
      "cc",
      "cp",
      "cxx",
      "h",
      "h++",
      "hh",
      "hpp",
      "hxx",
      "inc",
      "inl",
      "ipp",
      "tcc",
      "tpp",
    ],
    namingConvention: "PascalCase",
    prismTag: "cpp",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/e79bc8eb-f879-4ea3-93af-691ce90bc0d2",
  },
  {
    name: "Dart",
    fileExtension: ["dart"],
    namingConvention: "PascalCase",
    prismTag: "dart",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/f990d1d9-7ee7-4e5a-bf3a-4eb1e6114849",
  },
  {
    name: "F#",
    fileExtension: ["fs", "fsi", "fsx"],
    namingConvention: "PascalCase",
    prismTag: "fsharp",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/c79d9bed-7067-4307-aae3-0e70e4943bbd",
  },
  {
    name: "GO",
    fileExtension: ["go"],
    namingConvention: "snake_case",
    prismTag: "go",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/1daf9c41-f4de-44f8-9d0f-7fd1a2e39f86",
  },
  {
    name: "Haskell",
    fileExtension: ["hs", "hsc"],
    namingConvention: "snake_case",
    prismTag: "haskell",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/a3869f21-b3da-4cd8-98bb-982bf17c3116",
  },
  {
    name: "Java",
    fileExtension: ["java"],
    namingConvention: "PascalCase",
    prismTag: "java",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/c6ecb33d-7a88-4c95-aad0-5159f049171b",
  },
  {
    name: "JavaScript",
    fileExtension: [
      "js",
      "_js",
      "bones",
      "es",
      "es6",
      "frag",
      "gs",
      "jake",
      "jsb",
      "jscad",
      "jsfl",
      "jsm",
      "jss",
      "njs",
      "pac",
      "sjs",
      "ssjs",
      "sublime-build",
      "sublime-commands",
      "sublime-completions",
      "sublime-keymap",
      "sublime-macro",
      "sublime-menu",
      "sublime-mousemap",
      "sublime-project",
      "sublime-settings",
      "sublime-theme",
      "sublime-workspace",
      "sublime_metrics",
      "sublime_session",
      "xsjs",
      "xsjslib",
    ],
    namingConvention: "PascalCase",
    prismTag: "javascript",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/4174fe5f-31de-4e8e-866b-6433f3145278",
  },
  {
    name: "Julia",
    fileExtension: ["jl"],
    namingConvention: "snake_case",
    prismTag: "julia",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/cf51e1fd-a733-481c-b485-345fcc0208e3",
  },
  {
    name: "Kotlin",
    fileExtension: ["kt", "ktm", "kts"],
    namingConvention: "PascalCase",
    prismTag: "kotlin",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/3bc10026-1994-4be4-b2cb-d1e336f4b992",
  },
  {
    name: "Perl",
    fileExtension: [
      "pl",
      "al",
      "cgi",
      "fcgi",
      "perl",
      "ph",
      "plx",
      "pm",
      "pod",
      "psgi",
      "t",
    ],
    namingConvention: "snake_case",
    prismTag: "perl",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/f4a597ca-4c31-48d6-9cf6-61ca24ff75d6",
  },
  {
    name: "PHP",
    fileExtension: [
      "php",
      "aw",
      "ctp",
      "fcgi",
      "inc",
      "php3",
      "php4",
      "php5",
      "phps",
      "phpt",
    ],
    namingConvention: "snake_case",
    prismTag: "php",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/4ae69635-ed02-46a2-841b-4cea8a2c3b69",
  },
  {
    name: "Python",
    fileExtension: [
      "py",
      "bzl",
      "cgi",
      "fcgi",
      "gyp",
      "lmi",
      "pyde",
      "pyp",
      "pyt",
      "pyw",
      "rpy",
      "tac",
      "wsgi",
      "xpy",
    ],
    namingConvention: "snake_case",
    prismTag: "python",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/84788b04-f9ca-4201-b8fa-b097610ab2cf",
  },
  {
    name: "R",
    fileExtension: ["r", "rd", "rsx"],
    namingConvention: "snake_case",
    prismTag: "r",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/d171b379-c0c7-4f2a-80a1-873f51a76a4b",
  },
  {
    name: "Ruby",
    fileExtension: [
      "rb",
      "builder",
      "fcgi",
      "gemspec",
      "god",
      "irbrc",
      "jbuilder",
      "mspec",
      "pluginspec",
      "podspec",
      "rabl",
      "rake",
      "rbuild",
      "rbw",
      "rbx",
      "ru",
      "ruby",
      "thor",
      "watchr",
    ],
    namingConvention: "PascalCase",
    prismTag: "ruby",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/18d393ac-1921-4e39-9493-525fe7b3c660",
  },
  {
    name: "Rust",
    fileExtension: ["rs", "rs.in"],
    namingConvention: "snake_case",
    prismTag: "rust",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/d3e93dd8-7676-42e2-9699-8a4a8b5aa183",
  },
  {
    name: "Scala",
    fileExtension: ["scala", "sbt", "sc"],
    namingConvention: "camelCase",
    prismTag: "scala",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/229f44e6-3b48-42b9-8c99-65e8cb5a3ad1",
  },
  {
    name: "Swift",
    fileExtension: ["swift"],
    namingConvention: "PascalCase",
    prismTag: "swift",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/0cbe3e7a-f151-4bba-afc2-41a7944ab995",
  },
  {
    name: "TypeScript",
    fileExtension: ["ts", "tsx"],
    namingConvention: "PascalCase",
    prismTag: "typescript",
    logo: "https://github.com/codinasion/codinasion/assets/54644599/119c8a13-13bf-4d8c-91eb-0d8001bcbce5",
  },
];

export default LanguageData;
