#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Load config (variables)
. "$(dirname -- "$0")/config.sh"

echo ""
echo "${BLUE}INFO${NC}: ${YELLOW}Running post-merge hook${NC}"

echo ""
echo "${BLUE}INFO${NC}: ${YELLOW}Cloning submodules${NC}"
pnpm clone-submodules

echo ""
echo "${BLUE}INFO${NC}: ${YELLOW}Creating hard links${NC}"
ln -f docs/README.md README.md
ln -f docs/CODE_OF_CONDUCT.md CODE_OF_CONDUCT.md
ln -f docs/CONTRIBUTING.md CONTRIBUTING.md
