import type { LanguageDataType } from "../language-data/type";

const LanguageData: LanguageDataType[] = [
  {
    name: "C",
    fileExtension: ["c", "cats", "h", "idc", "w"],
    namingConvention: "PascalCase",
    prismTag: "c",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/c.png",
  },
  {
    name: "C#",
    fileExtension: ["cs", "cake", "cshtml", "csx"],
    namingConvention: "PascalCase",
    prismTag: "csharp",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/c-sharp.png",
  },
  {
    name: "C++",
    fileExtension: [
      "cpp",
      "c++",
      "cc",
      "cp",
      "cxx",
      "h",
      "h++",
      "hh",
      "hpp",
      "hxx",
      "inc",
      "inl",
      "ipp",
      "tcc",
      "tpp",
    ],
    namingConvention: "PascalCase",
    prismTag: "cpp",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/c-plus-plus.png",
  },
  {
    name: "Dart",
    fileExtension: ["dart"],
    namingConvention: "PascalCase",
    prismTag: "dart",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/dart.png",
  },
  {
    name: "F#",
    fileExtension: ["fs", "fsi", "fsx"],
    namingConvention: "PascalCase",
    prismTag: "fsharp",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/f-sharp.png",
  },
  {
    name: "GO",
    fileExtension: ["go"],
    namingConvention: "snake_case",
    prismTag: "go",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/go.png",
  },
  {
    name: "Haskell",
    fileExtension: ["hs", "hsc"],
    namingConvention: "snake_case",
    prismTag: "haskell",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/haskell.png",
  },
  {
    name: "Java",
    fileExtension: ["java"],
    namingConvention: "PascalCase",
    prismTag: "java",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/java.png",
  },
  {
    name: "JavaScript",
    fileExtension: [
      "js",
      "_js",
      "bones",
      "es",
      "es6",
      "frag",
      "gs",
      "jake",
      "jsb",
      "jscad",
      "jsfl",
      "jsm",
      "jss",
      "njs",
      "pac",
      "sjs",
      "ssjs",
      "sublime-build",
      "sublime-commands",
      "sublime-completions",
      "sublime-keymap",
      "sublime-macro",
      "sublime-menu",
      "sublime-mousemap",
      "sublime-project",
      "sublime-settings",
      "sublime-theme",
      "sublime-workspace",
      "sublime_metrics",
      "sublime_session",
      "xsjs",
      "xsjslib",
    ],
    namingConvention: "PascalCase",
    prismTag: "javascript",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/javascript.png",
  },
  {
    name: "Julia",
    fileExtension: ["jl"],
    namingConvention: "snake_case",
    prismTag: "julia",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/julia.png",
  },
  {
    name: "Kotlin",
    fileExtension: ["kt", "ktm", "kts"],
    namingConvention: "PascalCase",
    prismTag: "kotlin",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/kotlin.png",
  },
  {
    name: "Perl",
    fileExtension: [
      "pl",
      "al",
      "cgi",
      "fcgi",
      "perl",
      "ph",
      "plx",
      "pm",
      "pod",
      "psgi",
      "t",
    ],
    namingConvention: "snake_case",
    prismTag: "perl",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/perl.png",
  },
  {
    name: "PHP",
    fileExtension: [
      "php",
      "aw",
      "ctp",
      "fcgi",
      "inc",
      "php3",
      "php4",
      "php5",
      "phps",
      "phpt",
    ],
    namingConvention: "snake_case",
    prismTag: "php",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/php.png",
  },
  {
    name: "Python",
    fileExtension: [
      "py",
      "bzl",
      "cgi",
      "fcgi",
      "gyp",
      "lmi",
      "pyde",
      "pyp",
      "pyt",
      "pyw",
      "rpy",
      "tac",
      "wsgi",
      "xpy",
    ],
    namingConvention: "snake_case",
    prismTag: "python",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/python.png",
  },
  {
    name: "R",
    fileExtension: ["r", "rd", "rsx"],
    namingConvention: "snake_case",
    prismTag: "r",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/r.png",
  },
  {
    name: "Ruby",
    fileExtension: [
      "rb",
      "builder",
      "fcgi",
      "gemspec",
      "god",
      "irbrc",
      "jbuilder",
      "mspec",
      "pluginspec",
      "podspec",
      "rabl",
      "rake",
      "rbuild",
      "rbw",
      "rbx",
      "ru",
      "ruby",
      "thor",
      "watchr",
    ],
    namingConvention: "PascalCase",
    prismTag: "ruby",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/ruby.png",
  },
  {
    name: "Rust",
    fileExtension: ["rs", "rs.in"],
    namingConvention: "snake_case",
    prismTag: "rust",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/rust.png",
  },
  {
    name: "Scala",
    fileExtension: ["scala", "sbt", "sc"],
    namingConvention: "camelCase",
    prismTag: "scala",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/scala.png",
  },
  {
    name: "Swift",
    fileExtension: ["swift"],
    namingConvention: "PascalCase",
    prismTag: "swift",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/swift.png",
  },
  {
    name: "TypeScript",
    fileExtension: ["ts", "tsx"],
    namingConvention: "PascalCase",
    prismTag: "typescript",
    logo: "https://raw.githubusercontent.com/codinasion/codinasion/master/assets/language/typescript.png",
  },
];

export { LanguageData };
