name: Auto Track Issue
on:
  issues:
    types: [labeled]

jobs:
  auto_track_issue:
    if: github.event.label.name == 'auto-track'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Yarn
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          yarn

      - name: Issue data
        run: |
          echo "Issue number : ${{ github.event.issue.number }}"
          echo "Issue title  : ${{ github.event.issue.title }}"
          echo "Issue body   : ${{ github.event.issue.body }}"

      - name: Track Issue
        uses: ./action/
        with:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          AUTO_TRACK_ISSUE: true
          TOKEN: ${{ secrets.REPO_TOKEN }}
