# Add label 'hacktoberfest-accepted' to PRs that are merged
name: Auto Label
on:
  pull_request:
    types: [closed]

jobs:
  auto_label:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Yarn
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          yarn

      - name: Add Label
        uses: ./action/
        with:
          ISSUE_NUMBER: ${{ github.event.pull_request.number }}
          AUTO_ADD_LABEL: true
          TOKEN: ${{ secrets.PAT }}
