name: Auto Create DSA Issue
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0/1 * * *"

jobs:
  auto_create_dsa_issue:
    # run only if repo is not a fork
    if: github.repository == 'codinasion/program'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Yarn
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          yarn

      - name: Create Issue
        uses: ./action/
        with:
          AUTO_CREATE_DSA_ISSUE: true
          TOKEN: ${{ secrets.PAT }}

      - name: Git Pull
        run: |
          git pull

      - name: Commit DSA Data
        uses: EndBug/add-and-commit@v9
        with:
          add: "data/dsa.json"
          fetch: true
          message: "auto create issue"

      - name: Commit README
        uses: EndBug/add-and-commit@v9
        with:
          add: "dsa"
          fetch: true
          message: "add README.md"
