name: Submit DSA
on:
  issues:
    types: [labeled]

jobs:
  submit_dsa:
    if: github.event.label.name == 'submit-dsa' && github.event.issue.user.login == 'harshraj8843'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Yarn
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          yarn

      - name: Issue data
        run: |
          echo "Issue number : ${{ github.event.issue.number }}"
          echo "Issue title  : ${{ github.event.issue.title }}"
          echo "Issue body   : ${{ github.event.issue.body }}"
          echo "user         : ${{ github.event.issue.user.login }}"

      - name: Submit DSA
        id: submit-dsa
        uses: ./action/
        with:
          USERNAME: ${{ github.event.issue.user.login }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_LABEL: ${{ github.event.label.name }}
          SUBMIT_DSA: true
          TOKEN: ${{ secrets.PAT }}

      - name: Git Pull
        if: steps.submit-dsa.outputs.submit-success == 'true'
        run: |
          git pull

      - name: Commit DSA Data
        if: steps.submit-dsa.outputs.submit-success == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: "data/dsa.json"
          fetch: true
          message: "add new dsa - ${{ github.event.issue.user.login }}"

      - name: Comment & Close
        if: steps.submit-dsa.outputs.submit-success == 'true'
        uses: ./action/
        with:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_LABEL: ${{ github.event.label.name }}
          SUBMIT_DSA_COMMENT_CLOSE: true
          TOKEN: ${{ secrets.PAT }}
